
from .lib.proDEX import *

coach_mobility_use_stairs = Node()
Relative_change = Node()
situ_mobility_use_stairs = Atrib()
situ_mobility_use_stairs_predicted = Atrib()

coach_mobility_use_stairs.setName('coach_mobility_use_stairs')
Relative_change.setName('Relative_change')
situ_mobility_use_stairs.setName('situ_mobility_use_stairs')
situ_mobility_use_stairs_predicted.setName('situ_mobility_use_stairs_predicted')

coach_mobility_use_stairs.setValues(['negative_message_to_PU_or_SU', 'positive_message_to_PU_or_SU', 'no_action'])
Relative_change.setValues(['big_drop', 'medium_drop', 'small_drop', 'no_change', 'small_improvement', 'medium_improvement', 'big_improvement'])
situ_mobility_use_stairs.setValues(['very_low', 'low', 'medium', 'high', 'very_high'])
situ_mobility_use_stairs_predicted.setValues(['very_low', 'low', 'medium', 'high', 'very_high'])

coach_mobility_use_stairs.addChild(situ_mobility_use_stairs)
situ_mobility_use_stairs.setParent(coach_mobility_use_stairs)
coach_mobility_use_stairs.addChild(Relative_change)
Relative_change.setParent(coach_mobility_use_stairs)
Relative_change.addChild(situ_mobility_use_stairs)
situ_mobility_use_stairs.setParent(Relative_change)
Relative_change.addChild(situ_mobility_use_stairs_predicted)
situ_mobility_use_stairs_predicted.setParent(Relative_change)

coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'very_low', Relative_change:'big_drop'}, 'negative_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'very_low', Relative_change:'medium_drop'}, 'negative_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'very_low', Relative_change:'small_drop'}, 'negative_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'very_low', Relative_change:'no_change'}, 'no_action'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'very_low', Relative_change:'small_improvement'}, 'no_action'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'very_low', Relative_change:'medium_improvement'}, 'no_action'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'very_low', Relative_change:'big_improvement'}, 'no_action'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'low', Relative_change:'big_drop'}, 'negative_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'low', Relative_change:'medium_drop'}, 'negative_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'low', Relative_change:'small_drop'}, 'negative_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'low', Relative_change:'no_change'}, 'no_action'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'low', Relative_change:'small_improvement'}, 'positive_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'low', Relative_change:'medium_improvement'}, 'positive_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'low', Relative_change:'big_improvement'}, 'positive_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'medium', Relative_change:'big_drop'}, 'negative_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'medium', Relative_change:'medium_drop'}, 'negative_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'medium', Relative_change:'small_drop'}, 'negative_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'medium', Relative_change:'no_change'}, 'no_action'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'medium', Relative_change:'small_improvement'}, 'positive_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'medium', Relative_change:'medium_improvement'}, 'positive_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'medium', Relative_change:'big_improvement'}, 'positive_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'high', Relative_change:'big_drop'}, 'negative_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'high', Relative_change:'medium_drop'}, 'negative_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'high', Relative_change:'small_drop'}, 'negative_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'high', Relative_change:'no_change'}, 'no_action'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'high', Relative_change:'small_improvement'}, 'positive_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'high', Relative_change:'medium_improvement'}, 'positive_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'high', Relative_change:'big_improvement'}, 'positive_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'very_high', Relative_change:'big_drop'}, 'no_action'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'very_high', Relative_change:'medium_drop'}, 'no_action'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'very_high', Relative_change:'small_drop'}, 'no_action'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'very_high', Relative_change:'no_change'}, 'no_action'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'very_high', Relative_change:'small_improvement'}, 'no_action'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'very_high', Relative_change:'medium_improvement'}, 'positive_message_to_PU_or_SU'])
coach_mobility_use_stairs.addFunctionRow([{situ_mobility_use_stairs:'very_high', Relative_change:'big_improvement'}, 'positive_message_to_PU_or_SU'])

Relative_change.addFunctionRow([{situ_mobility_use_stairs:'very_low', situ_mobility_use_stairs_predicted:'very_low'}, 'no_change'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'very_low', situ_mobility_use_stairs_predicted:'low'}, 'small_drop'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'very_low', situ_mobility_use_stairs_predicted:'medium'}, 'big_drop'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'very_low', situ_mobility_use_stairs_predicted:'high'}, 'big_drop'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'very_low', situ_mobility_use_stairs_predicted:'very_high'}, 'big_drop'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'low', situ_mobility_use_stairs_predicted:'very_low'}, 'small_improvement'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'low', situ_mobility_use_stairs_predicted:'low'}, 'no_change'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'low', situ_mobility_use_stairs_predicted:'medium'}, 'small_drop'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'low', situ_mobility_use_stairs_predicted:'high'}, 'big_drop'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'low', situ_mobility_use_stairs_predicted:'very_high'}, 'big_drop'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'medium', situ_mobility_use_stairs_predicted:'very_low'}, 'big_improvement'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'medium', situ_mobility_use_stairs_predicted:'low'}, 'small_improvement'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'medium', situ_mobility_use_stairs_predicted:'medium'}, 'no_change'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'medium', situ_mobility_use_stairs_predicted:'high'}, 'small_drop'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'medium', situ_mobility_use_stairs_predicted:'very_high'}, 'big_drop'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'high', situ_mobility_use_stairs_predicted:'very_low'}, 'big_improvement'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'high', situ_mobility_use_stairs_predicted:'low'}, 'big_improvement'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'high', situ_mobility_use_stairs_predicted:'medium'}, 'small_improvement'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'high', situ_mobility_use_stairs_predicted:'high'}, 'no_change'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'high', situ_mobility_use_stairs_predicted:'very_high'}, 'small_drop'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'very_high', situ_mobility_use_stairs_predicted:'very_low'}, 'big_improvement'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'very_high', situ_mobility_use_stairs_predicted:'low'}, 'big_improvement'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'very_high', situ_mobility_use_stairs_predicted:'medium'}, 'small_improvement'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'very_high', situ_mobility_use_stairs_predicted:'high'}, 'small_improvement'])
Relative_change.addFunctionRow([{situ_mobility_use_stairs:'very_high', situ_mobility_use_stairs_predicted:'very_high'}, 'no_change'])

