##################################################################################
##########--this is an autogenerated python model definition for proDEX--#########
##--original file: coach_activity_cooking.dxi --##
##################################################################################

from .lib.proDEX import *

coach_activity_cooking = Node()
situ_activity_cooking = Atrib()

coach_activity_cooking.setName('coach_activity_cooking')
situ_activity_cooking.setName('situ_activity_cooking')

coach_activity_cooking.setValues(['positive_message_to_PU_or_SU', 'negative_message_to_SU_or_PU', 'no_action'])
situ_activity_cooking.setValues(['less_cooking', 'usual_cooking', 'more_cooking'])

coach_activity_cooking.addChild(situ_activity_cooking)
situ_activity_cooking.setParent(coach_activity_cooking)

coach_activity_cooking.addFunctionRow([{situ_activity_cooking:'less_cooking'}, 'negative_message_to_SU_or_PU'])
coach_activity_cooking.addFunctionRow([{situ_activity_cooking:'usual_cooking'}, 'no_action'])
coach_activity_cooking.addFunctionRow([{situ_activity_cooking:'more_cooking'}, 'positive_message_to_PU_or_SU'])

