##################################################################################
##########--this is an autogenerated python model definition for proDEX--#########
##--original file: situ_activity_outside_simplified4levels.dxi --##
##################################################################################

from .lib.proDEX import *

situ_activity_outside = Node()
Time_outside = Node()
Predicted_time_outside = Node()
feat_activity_outside_recorded = Atrib()
feat_activity_outside_predicted = Atrib()

situ_activity_outside.setName('situ_activity_outside')
Time_outside.setName('Time_outside')
Predicted_time_outside.setName('Predicted_time_outside')
feat_activity_outside_recorded.setName('feat_activity_outside_recorded')
feat_activity_outside_predicted.setName('feat_activity_outside_predicted')

situ_activity_outside.setValues(['less_outside', 'usual_outside', 'more_outside'])
Time_outside.setValues(['low', 'medium', 'high', 'very_high'])
Predicted_time_outside.setValues(['low', 'medium', 'high', 'very_high'])
feat_activity_outside_recorded.setValues(['less_than_1h', '1h_to_2h', '2h_to_5h', 'more_than_5h'])
feat_activity_outside_predicted.setValues(['less_than_1h', '1h_to_2h', '2h_to_5h', 'more_than_5h'])

situ_activity_outside.addChild(Time_outside)
Time_outside.setParent(situ_activity_outside)
situ_activity_outside.addChild(Predicted_time_outside)
Predicted_time_outside.setParent(situ_activity_outside)
Time_outside.addChild(feat_activity_outside_recorded)
feat_activity_outside_recorded.setParent(Time_outside)
Predicted_time_outside.addChild(feat_activity_outside_predicted)
feat_activity_outside_predicted.setParent(Predicted_time_outside)

situ_activity_outside.addFunctionRow([{Time_outside:'low', Predicted_time_outside:'low'}, 'usual_outside'])
situ_activity_outside.addFunctionRow([{Time_outside:'low', Predicted_time_outside:'medium'}, 'less_outside'])
situ_activity_outside.addFunctionRow([{Time_outside:'low', Predicted_time_outside:'high'}, 'less_outside'])
situ_activity_outside.addFunctionRow([{Time_outside:'low', Predicted_time_outside:'very_high'}, 'less_outside'])
situ_activity_outside.addFunctionRow([{Time_outside:'medium', Predicted_time_outside:'low'}, 'more_outside'])
situ_activity_outside.addFunctionRow([{Time_outside:'medium', Predicted_time_outside:'medium'}, 'usual_outside'])
situ_activity_outside.addFunctionRow([{Time_outside:'medium', Predicted_time_outside:'high'}, 'less_outside'])
situ_activity_outside.addFunctionRow([{Time_outside:'medium', Predicted_time_outside:'very_high'}, 'less_outside'])
situ_activity_outside.addFunctionRow([{Time_outside:'high', Predicted_time_outside:'low'}, 'more_outside'])
situ_activity_outside.addFunctionRow([{Time_outside:'high', Predicted_time_outside:'medium'}, 'more_outside'])
situ_activity_outside.addFunctionRow([{Time_outside:'high', Predicted_time_outside:'high'}, 'usual_outside'])
situ_activity_outside.addFunctionRow([{Time_outside:'high', Predicted_time_outside:'very_high'}, 'less_outside'])
situ_activity_outside.addFunctionRow([{Time_outside:'very_high', Predicted_time_outside:'low'}, 'more_outside'])
situ_activity_outside.addFunctionRow([{Time_outside:'very_high', Predicted_time_outside:'medium'}, 'more_outside'])
situ_activity_outside.addFunctionRow([{Time_outside:'very_high', Predicted_time_outside:'high'}, 'more_outside'])
situ_activity_outside.addFunctionRow([{Time_outside:'very_high', Predicted_time_outside:'very_high'}, 'usual_outside'])

Time_outside.addFunctionRow([{feat_activity_outside_recorded:'less_than_1h'}, 'low'])
Time_outside.addFunctionRow([{feat_activity_outside_recorded:'1h_to_2h'}, 'medium'])
Time_outside.addFunctionRow([{feat_activity_outside_recorded:'2h_to_5h'}, 'high'])
Time_outside.addFunctionRow([{feat_activity_outside_recorded:'more_than_5h'}, 'very_high'])

Predicted_time_outside.addFunctionRow([{feat_activity_outside_predicted:'less_than_1h'}, 'low'])
Predicted_time_outside.addFunctionRow([{feat_activity_outside_predicted:'1h_to_2h'}, 'medium'])
Predicted_time_outside.addFunctionRow([{feat_activity_outside_predicted:'2h_to_5h'}, 'high'])
Predicted_time_outside.addFunctionRow([{feat_activity_outside_predicted:'more_than_5h'}, 'very_high'])

