
from .lib.proDEX import *

situ_mobility_use_stairs = Node()
Resting_during = Node()
feat_mobility_use_stairs_mode = Atrib()
feat_mobility_use_stairs_count = Atrib()
feat_mobility_use_stairs_time_per = Atrib()
feat_mobility_use_stairs_rest_count = Atrib()
feat_mobility_use_stairs_rest_duration = Atrib()

situ_mobility_use_stairs.setName('situ_mobility_use_stairs')
Resting_during.setName('Resting_during')
feat_mobility_use_stairs_mode.setName('feat_mobility_use_stairs_mode')
feat_mobility_use_stairs_count.setName('feat_mobility_use_stairs_count')
feat_mobility_use_stairs_time_per.setName('feat_mobility_use_stairs_time_per')
feat_mobility_use_stairs_rest_count.setName('feat_mobility_use_stairs_rest_count')
feat_mobility_use_stairs_rest_duration.setName('feat_mobility_use_stairs_rest_duration')

situ_mobility_use_stairs.setValues(['very_low', 'low', 'medium', 'high', 'very_high'])
Resting_during.setValues(['significant', 'medium', 'negligable'])
feat_mobility_use_stairs_mode.setValues(['mostly_aided', 'mixed', 'mostly_unaided'])
feat_mobility_use_stairs_count.setValues(['few', 'many'])
feat_mobility_use_stairs_time_per.setValues(['long', 'short'])
feat_mobility_use_stairs_rest_count.setValues(['several', 'few'])
feat_mobility_use_stairs_rest_duration.setValues(['long', 'short'])

situ_mobility_use_stairs.addChild(feat_mobility_use_stairs_mode)
feat_mobility_use_stairs_mode.setParent(situ_mobility_use_stairs)
situ_mobility_use_stairs.addChild(feat_mobility_use_stairs_count)
feat_mobility_use_stairs_count.setParent(situ_mobility_use_stairs)
situ_mobility_use_stairs.addChild(feat_mobility_use_stairs_time_per)
feat_mobility_use_stairs_time_per.setParent(situ_mobility_use_stairs)
situ_mobility_use_stairs.addChild(Resting_during)
Resting_during.setParent(situ_mobility_use_stairs)
Resting_during.addChild(feat_mobility_use_stairs_rest_count)
feat_mobility_use_stairs_rest_count.setParent(Resting_during)
Resting_during.addChild(feat_mobility_use_stairs_rest_duration)
feat_mobility_use_stairs_rest_duration.setParent(Resting_during)

situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_aided', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'long', Resting_during:'significant'}, 'very_low'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_aided', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'long', Resting_during:'medium'}, 'very_low'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_aided', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'long', Resting_during:'negligable'}, 'low'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_aided', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'short', Resting_during:'significant'}, 'very_low'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_aided', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'short', Resting_during:'medium'}, 'low'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_aided', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'short', Resting_during:'negligable'}, 'medium'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_aided', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'long', Resting_during:'significant'}, 'very_low'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_aided', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'long', Resting_during:'medium'}, 'very_low'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_aided', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'long', Resting_during:'negligable'}, 'low'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_aided', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'short', Resting_during:'significant'}, 'low'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_aided', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'short', Resting_during:'medium'}, 'low'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_aided', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'short', Resting_during:'negligable'}, 'medium'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mixed', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'long', Resting_during:'significant'}, 'very_low'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mixed', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'long', Resting_during:'medium'}, 'very_low'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mixed', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'long', Resting_during:'negligable'}, 'low'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mixed', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'short', Resting_during:'significant'}, 'low'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mixed', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'short', Resting_during:'medium'}, 'medium'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mixed', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'short', Resting_during:'negligable'}, 'medium'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mixed', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'long', Resting_during:'significant'}, 'low'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mixed', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'long', Resting_during:'medium'}, 'low'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mixed', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'long', Resting_during:'negligable'}, 'medium'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mixed', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'short', Resting_during:'significant'}, 'medium'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mixed', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'short', Resting_during:'medium'}, 'medium'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mixed', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'short', Resting_during:'negligable'}, 'high'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_unaided', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'long', Resting_during:'significant'}, 'medium'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_unaided', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'long', Resting_during:'medium'}, 'medium'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_unaided', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'long', Resting_during:'negligable'}, 'medium'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_unaided', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'short', Resting_during:'significant'}, 'medium'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_unaided', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'short', Resting_during:'medium'}, 'medium'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_unaided', feat_mobility_use_stairs_count:'few', feat_mobility_use_stairs_time_per:'short', Resting_during:'negligable'}, 'high'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_unaided', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'long', Resting_during:'significant'}, 'medium'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_unaided', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'long', Resting_during:'medium'}, 'high'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_unaided', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'long', Resting_during:'negligable'}, 'high'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_unaided', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'short', Resting_during:'significant'}, 'high'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_unaided', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'short', Resting_during:'medium'}, 'high'])
situ_mobility_use_stairs.addFunctionRow([{feat_mobility_use_stairs_mode:'mostly_unaided', feat_mobility_use_stairs_count:'many', feat_mobility_use_stairs_time_per:'short', Resting_during:'negligable'}, 'very_high'])

Resting_during.addFunctionRow([{feat_mobility_use_stairs_rest_count:'several', feat_mobility_use_stairs_rest_duration:'long'}, 'significant'])
Resting_during.addFunctionRow([{feat_mobility_use_stairs_rest_count:'several', feat_mobility_use_stairs_rest_duration:'short'}, 'medium'])
Resting_during.addFunctionRow([{feat_mobility_use_stairs_rest_count:'few', feat_mobility_use_stairs_rest_duration:'long'}, 'medium'])
Resting_during.addFunctionRow([{feat_mobility_use_stairs_rest_count:'few', feat_mobility_use_stairs_rest_duration:'short'}, 'negligable'])

