##################################################################################
##########--this is an autogenerated python model definition for proDEX--#########
##--original file: situ_mobility_instructed_walking.dxi --##
##################################################################################

from .lib.proDEX import *

situ_mobility_instructed_walking = Node()
feat_walking_longest_episode_exceeded = Atrib()
feat_walking_time_threshold_reached = Atrib()

situ_mobility_instructed_walking.setName('situ_mobility_instructed_walking')
feat_walking_longest_episode_exceeded.setName('feat_walking_longest_episode_exceeded')
feat_walking_time_threshold_reached.setName('feat_walking_time_threshold_reached')

situ_mobility_instructed_walking.setValues(['as_instructed', 'too_long_episode', 'too_long_cumulative', 'too_long_episode_and_cumulative'])
feat_walking_longest_episode_exceeded.setValues(['exceeded', 'in_limits'])
feat_walking_time_threshold_reached.setValues(['yes', 'no'])

situ_mobility_instructed_walking.addChild(feat_walking_longest_episode_exceeded)
feat_walking_longest_episode_exceeded.setParent(situ_mobility_instructed_walking)
situ_mobility_instructed_walking.addChild(feat_walking_time_threshold_reached)
feat_walking_time_threshold_reached.setParent(situ_mobility_instructed_walking)

situ_mobility_instructed_walking.addFunctionRow([{feat_walking_longest_episode_exceeded:'exceeded', feat_walking_time_threshold_reached:'yes'}, 'too_long_episode_and_cumulative'])
situ_mobility_instructed_walking.addFunctionRow([{feat_walking_longest_episode_exceeded:'exceeded', feat_walking_time_threshold_reached:'no'}, 'too_long_episode'])
situ_mobility_instructed_walking.addFunctionRow([{feat_walking_longest_episode_exceeded:'in_limits', feat_walking_time_threshold_reached:'yes'}, 'too_long_cumulative'])
situ_mobility_instructed_walking.addFunctionRow([{feat_walking_longest_episode_exceeded:'in_limits', feat_walking_time_threshold_reached:'no'}, 'as_instructed'])

