##################################################################################
##########--this is an autogenerated python model definition for proDEX--#########
##--original file: Mobility_general_v02.dxi --##
##################################################################################

from .lib.proDEX import *

situ_mobility_stand_up = Node()
feat_mobility_stand_up_count = Atrib()
feat_mobility_stand_up_mode = Atrib()
feat_mobility_stand_up_time = Atrib()

situ_mobility_stand_up.setName('situ_mobility_stand_up')
feat_mobility_stand_up_count.setName('feat_mobility_stand_up_count')
feat_mobility_stand_up_mode.setName('feat_mobility_stand_up_mode')
feat_mobility_stand_up_time.setName('feat_mobility_stand_up_time')

situ_mobility_stand_up.setValues(['very_low', 'low', 'medium', 'high', 'very_high'])
feat_mobility_stand_up_count.setValues(['low', 'medium', 'high'])
feat_mobility_stand_up_mode.setValues(['with_hands', 'no_hands'])
feat_mobility_stand_up_time.setValues(['slow', 'fast'])

situ_mobility_stand_up.addChild(feat_mobility_stand_up_count)
feat_mobility_stand_up_count.setParent(situ_mobility_stand_up)
situ_mobility_stand_up.addChild(feat_mobility_stand_up_mode)
feat_mobility_stand_up_mode.setParent(situ_mobility_stand_up)
situ_mobility_stand_up.addChild(feat_mobility_stand_up_time)
feat_mobility_stand_up_time.setParent(situ_mobility_stand_up)


situ_mobility_stand_up.addFunctionRow([{feat_mobility_stand_up_count:'low', feat_mobility_stand_up_mode:'with_hands', feat_mobility_stand_up_time:'slow'}, 'very_low'])
situ_mobility_stand_up.addFunctionRow([{feat_mobility_stand_up_count:'low', feat_mobility_stand_up_mode:'with_hands', feat_mobility_stand_up_time:'fast'}, 'very_low'])
situ_mobility_stand_up.addFunctionRow([{feat_mobility_stand_up_count:'low', feat_mobility_stand_up_mode:'no_hands', feat_mobility_stand_up_time:'slow'}, 'low'])
situ_mobility_stand_up.addFunctionRow([{feat_mobility_stand_up_count:'low', feat_mobility_stand_up_mode:'no_hands', feat_mobility_stand_up_time:'fast'}, 'medium'])
situ_mobility_stand_up.addFunctionRow([{feat_mobility_stand_up_count:'medium', feat_mobility_stand_up_mode:'with_hands', feat_mobility_stand_up_time:'slow'}, 'very_low'])
situ_mobility_stand_up.addFunctionRow([{feat_mobility_stand_up_count:'medium', feat_mobility_stand_up_mode:'with_hands', feat_mobility_stand_up_time:'fast'}, 'low'])
situ_mobility_stand_up.addFunctionRow([{feat_mobility_stand_up_count:'medium', feat_mobility_stand_up_mode:'no_hands', feat_mobility_stand_up_time:'slow'}, 'low'])
situ_mobility_stand_up.addFunctionRow([{feat_mobility_stand_up_count:'medium', feat_mobility_stand_up_mode:'no_hands', feat_mobility_stand_up_time:'fast'}, 'high'])
situ_mobility_stand_up.addFunctionRow([{feat_mobility_stand_up_count:'high', feat_mobility_stand_up_mode:'with_hands', feat_mobility_stand_up_time:'slow'}, 'low'])
situ_mobility_stand_up.addFunctionRow([{feat_mobility_stand_up_count:'high', feat_mobility_stand_up_mode:'with_hands', feat_mobility_stand_up_time:'fast'}, 'medium'])
situ_mobility_stand_up.addFunctionRow([{feat_mobility_stand_up_count:'high', feat_mobility_stand_up_mode:'no_hands', feat_mobility_stand_up_time:'slow'}, 'medium'])
situ_mobility_stand_up.addFunctionRow([{feat_mobility_stand_up_count:'high', feat_mobility_stand_up_mode:'no_hands', feat_mobility_stand_up_time:'fast'}, 'very_high'])

