##################################################################################
##########--this is an autogenerated python model definition for proDEX--#########
##--original file: Community_Involvement_Assessment_v05.dxi --##
##################################################################################

from .lib.proDEX import *

situ_social_activity_community = Node()
feat_community_habitual_weekly_vs_goal = Atrib()
feat_community_habitual_relative = Atrib()
feat_community_nonhabitual = Atrib()

situ_social_activity_community.setName('situ_social_activity_community')
feat_community_habitual_weekly_vs_goal.setName('feat_community_habitual_weekly_vs_goal')
feat_community_habitual_relative.setName('feat_community_habitual_relative')
feat_community_nonhabitual.setName('feat_community_nonhabitual')

situ_social_activity_community.setValues(['very_low', 'low', 'medium', 'high', 'very_high'])
feat_community_habitual_weekly_vs_goal.setValues(['low', 'medium', 'high'])
feat_community_habitual_relative.setValues(['decrease', 'stable', 'increase'])
feat_community_nonhabitual.setValues(['at_none', 'at_some', 'at_all'])

situ_social_activity_community.addChild(feat_community_habitual_weekly_vs_goal)
feat_community_habitual_weekly_vs_goal.setParent(situ_social_activity_community)
situ_social_activity_community.addChild(feat_community_habitual_relative)
feat_community_habitual_relative.setParent(situ_social_activity_community)
situ_social_activity_community.addChild(feat_community_nonhabitual)
feat_community_nonhabitual.setParent(situ_social_activity_community)

situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'low', feat_community_habitual_relative:'decrease', feat_community_nonhabitual:'at_none'}, 'very_low'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'low', feat_community_habitual_relative:'decrease', feat_community_nonhabitual:'at_some'}, 'very_low'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'low', feat_community_habitual_relative:'decrease', feat_community_nonhabitual:'at_all'}, 'very_low'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'low', feat_community_habitual_relative:'stable', feat_community_nonhabitual:'at_none'}, 'low'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'low', feat_community_habitual_relative:'stable', feat_community_nonhabitual:'at_some'}, 'low'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'low', feat_community_habitual_relative:'stable', feat_community_nonhabitual:'at_all'}, 'medium'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'low', feat_community_habitual_relative:'increase', feat_community_nonhabitual:'at_none'}, 'medium'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'low', feat_community_habitual_relative:'increase', feat_community_nonhabitual:'at_some'}, 'medium'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'low', feat_community_habitual_relative:'increase', feat_community_nonhabitual:'at_all'}, 'high'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'medium', feat_community_habitual_relative:'decrease', feat_community_nonhabitual:'at_none'}, 'low'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'medium', feat_community_habitual_relative:'decrease', feat_community_nonhabitual:'at_some'}, 'medium'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'medium', feat_community_habitual_relative:'decrease', feat_community_nonhabitual:'at_all'}, 'medium'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'medium', feat_community_habitual_relative:'stable', feat_community_nonhabitual:'at_none'}, 'medium'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'medium', feat_community_habitual_relative:'stable', feat_community_nonhabitual:'at_some'}, 'medium'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'medium', feat_community_habitual_relative:'stable', feat_community_nonhabitual:'at_all'}, 'high'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'medium', feat_community_habitual_relative:'increase', feat_community_nonhabitual:'at_none'}, 'medium'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'medium', feat_community_habitual_relative:'increase', feat_community_nonhabitual:'at_some'}, 'high'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'medium', feat_community_habitual_relative:'increase', feat_community_nonhabitual:'at_all'}, 'high'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'high', feat_community_habitual_relative:'decrease', feat_community_nonhabitual:'at_none'}, 'medium'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'high', feat_community_habitual_relative:'decrease', feat_community_nonhabitual:'at_some'}, 'high'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'high', feat_community_habitual_relative:'decrease', feat_community_nonhabitual:'at_all'}, 'high'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'high', feat_community_habitual_relative:'stable', feat_community_nonhabitual:'at_none'}, 'high'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'high', feat_community_habitual_relative:'stable', feat_community_nonhabitual:'at_some'}, 'very_high'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'high', feat_community_habitual_relative:'stable', feat_community_nonhabitual:'at_all'}, 'very_high'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'high', feat_community_habitual_relative:'increase', feat_community_nonhabitual:'at_none'}, 'high'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'high', feat_community_habitual_relative:'increase', feat_community_nonhabitual:'at_some'}, 'very_high'])
situ_social_activity_community.addFunctionRow([{feat_community_habitual_weekly_vs_goal:'high', feat_community_habitual_relative:'increase', feat_community_nonhabitual:'at_all'}, 'very_high'])

