##################################################################################
##########--this is an autogenerated python model definition for proDEX--#########
##--original file: Mobility_general_v02.dxi --##
##################################################################################

from .lib.proDEX import *

situ_mobility_standing = Node()
feat_mobility_standing_episode_length = Atrib()
feat_mobility_standing_daily_duration = Atrib()
feat_mobility_standing_mode = Atrib()

situ_mobility_standing.setName('situ_mobility_standing')
feat_mobility_standing_episode_length.setName('feat_mobility_standing_episode_length')
feat_mobility_standing_daily_duration.setName('feat_mobility_standing_daily_duration')
feat_mobility_standing_mode.setName('feat_mobility_standing_mode')

situ_mobility_standing.setValues(['very_low', 'low', 'medium', 'high', 'very_high'])
feat_mobility_standing_episode_length.setValues(['short', 'medium', 'long'])
feat_mobility_standing_daily_duration.setValues(['low', 'medium', 'high'])
feat_mobility_standing_mode.setValues(['with_aids', 'no_aids'])

situ_mobility_standing.addChild(feat_mobility_standing_episode_length)
feat_mobility_standing_episode_length.setParent(situ_mobility_standing)
situ_mobility_standing.addChild(feat_mobility_standing_daily_duration)
feat_mobility_standing_daily_duration.setParent(situ_mobility_standing)
situ_mobility_standing.addChild(feat_mobility_standing_mode)
feat_mobility_standing_mode.setParent(situ_mobility_standing)

situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'short', feat_mobility_standing_daily_duration:'low', feat_mobility_standing_mode:'with_aids'}, 'very_low'])
situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'short', feat_mobility_standing_daily_duration:'low', feat_mobility_standing_mode:'no_aids'}, 'low'])
situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'short', feat_mobility_standing_daily_duration:'medium', feat_mobility_standing_mode:'with_aids'}, 'very_low'])
situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'short', feat_mobility_standing_daily_duration:'medium', feat_mobility_standing_mode:'no_aids'}, 'low'])
situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'short', feat_mobility_standing_daily_duration:'high', feat_mobility_standing_mode:'with_aids'}, 'low'])
situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'short', feat_mobility_standing_daily_duration:'high', feat_mobility_standing_mode:'no_aids'}, 'medium'])
situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'medium', feat_mobility_standing_daily_duration:'low', feat_mobility_standing_mode:'with_aids'}, 'low'])
situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'medium', feat_mobility_standing_daily_duration:'low', feat_mobility_standing_mode:'no_aids'}, 'medium'])
situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'medium', feat_mobility_standing_daily_duration:'medium', feat_mobility_standing_mode:'with_aids'}, 'medium'])
situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'medium', feat_mobility_standing_daily_duration:'medium', feat_mobility_standing_mode:'no_aids'}, 'medium'])
situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'medium', feat_mobility_standing_daily_duration:'high', feat_mobility_standing_mode:'with_aids'}, 'medium'])
situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'medium', feat_mobility_standing_daily_duration:'high', feat_mobility_standing_mode:'no_aids'}, 'high'])
situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'long', feat_mobility_standing_daily_duration:'low', feat_mobility_standing_mode:'with_aids'}, 'medium'])
situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'long', feat_mobility_standing_daily_duration:'low', feat_mobility_standing_mode:'no_aids'}, 'high'])
situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'long', feat_mobility_standing_daily_duration:'medium', feat_mobility_standing_mode:'with_aids'}, 'medium'])
situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'long', feat_mobility_standing_daily_duration:'medium', feat_mobility_standing_mode:'no_aids'}, 'high'])
situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'long', feat_mobility_standing_daily_duration:'high', feat_mobility_standing_mode:'with_aids'}, 'medium'])
situ_mobility_standing.addFunctionRow([{feat_mobility_standing_episode_length:'long', feat_mobility_standing_daily_duration:'high', feat_mobility_standing_mode:'no_aids'}, 'very_high'])

