##################################################################################
##########--this is an autogenerated python model definition for proDEX--#########
##--original file: situ_activity_cooking.dxi --##
##################################################################################

from .lib.proDEX import *

situ_activity_cooking = Node()
feat_cooking_recorded = Atrib()
feat_cooking_predicted = Atrib()

situ_activity_cooking.setName('situ_activity_cooking')
feat_cooking_recorded.setName('feat_cooking_recorded')
feat_cooking_predicted.setName('feat_cooking_predicted')

situ_activity_cooking.setValues(['less_cooking', 'usual_cooking', 'more_cooking'])
feat_cooking_recorded.setValues(['none', 'once', 'twice_or_more'])
feat_cooking_predicted.setValues(['none', 'once', 'twice_or_more'])

situ_activity_cooking.addChild(feat_cooking_recorded)
feat_cooking_recorded.setParent(situ_activity_cooking)
situ_activity_cooking.addChild(feat_cooking_predicted)
feat_cooking_predicted.setParent(situ_activity_cooking)

situ_activity_cooking.addFunctionRow([{feat_cooking_recorded:'none', feat_cooking_predicted:'none'}, 'usual_cooking'])
situ_activity_cooking.addFunctionRow([{feat_cooking_recorded:'none', feat_cooking_predicted:'once'}, 'less_cooking'])
situ_activity_cooking.addFunctionRow([{feat_cooking_recorded:'none', feat_cooking_predicted:'twice_or_more'}, 'less_cooking'])
situ_activity_cooking.addFunctionRow([{feat_cooking_recorded:'once', feat_cooking_predicted:'none'}, 'more_cooking'])
situ_activity_cooking.addFunctionRow([{feat_cooking_recorded:'once', feat_cooking_predicted:'once'}, 'usual_cooking'])
situ_activity_cooking.addFunctionRow([{feat_cooking_recorded:'once', feat_cooking_predicted:'twice_or_more'}, 'less_cooking'])
situ_activity_cooking.addFunctionRow([{feat_cooking_recorded:'twice_or_more', feat_cooking_predicted:'none'}, 'more_cooking'])
situ_activity_cooking.addFunctionRow([{feat_cooking_recorded:'twice_or_more', feat_cooking_predicted:'once'}, 'more_cooking'])
situ_activity_cooking.addFunctionRow([{feat_cooking_recorded:'twice_or_more', feat_cooking_predicted:'twice_or_more'}, 'usual_cooking'])

